Clean up script, add check for required commands.

diff --git a/bin/generate_docs b/bin/generate_docs
--- a/bin/generate_docs
+++ b/bin/generate_docs
@@ -1,19 +1,20 @@
 #!/bin/sh
 
+# Check for required commands: doxygen, xsltproc
+command -v doxygen >/dev/null 2>&1 || { echo >&2 "I require the command 'doxygen' but it's not installed.  Aborting."; exit 1; }
+command -v xsltproc >/dev/null 2>&1 || { echo >&2 "I require the command 'xsltproc' but it's not installed.  Aborting."; exit 1; }
+command -v dot >/dev/null 2>&1 || { echo >&2 "I require the command 'dot' but it's not installed.  Aborting."; exit 1; }
+
 BIN=`dirname $0`
 cd $BIN
 cd ..
 TOP=`pwd`
-#SRC=$TOP/srs
 SRC=$TOP/include 
 workdir=$TOP/IncludeTemp
 
 if [ ! -d $workdir ]; then
    mkdir $workdir
 fi
-
-LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib/graphviz"
-export LD_LIBRARY_PATH
 
 # start with a clean slate
 cd $workdir
@@ -63,10 +64,7 @@ done
 cd $TOP/doc
 cp *.{doc,html} $workdir
 
-
 cd $TOP
-#doxygen $TOP/config/qicstable.cfg
-#/ICS/Users/craig/tmp/doxygen-1.3.2/bin/doxygen $TOP/config/qicstable.cfg
 doxygen $TOP/config/qicstable.cfg
 xsltproc $TOP/config/tag2dcf.xsl $TOP/doc/qicstable.tag > $TOP/doc/QicsTable.dcf
 
